
name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macOS-15

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
  
      - name: Build
        run: swift build -v

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Android"
        uses: skiptools/swift-android-action@v2
        with:
          run-tests: false
