name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: ./create-xcframework.sh

    - name: Upload binaries to release
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Artifacts
        path: ./artifacts

    - name: Create Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: artifacts/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}