name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: ./create-xcframework.sh

    - name: Upload binaries to release
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Artifacts
        path: ./artifacts
    
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/LogKit.xcframework"
        token: ${{ secrets.GITHUB_TOKEN }}