name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: ./create-xcframework.sh
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: LogKit.xcframework
        asset_name: LogKit.xcframework
        tag: ${{ github.ref }}
        overwrite: true