
name: Swift

on: [push]

jobs:
  SwiftLint:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict

  build:
    name: Build
    runs-on: macOS-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
  
      - name: Build
        run: swift build -v
      
  test:
    name: Test
    runs-on: macOS-latest
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - run: swift test -v --enable-test-discovery --enable-code-coverage --sanitize=thread
