
name: Test

on:
  push:
    branches: '*'
    tags-ignore: '*'

jobs:
  swiftlint:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict

  test:
    name: Test
    runs-on: macOS-latest
      
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Test
        run: swift test -v --enable-test-discovery --enable-code-coverage --sanitize=thread