
name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
      
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Test
        run: swift test -v --enable-test-discovery --enable-code-coverage --sanitize=thread