
name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macOS-15
      
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Test
        run: swift test -v --enable-test-discovery --enable-code-coverage --sanitize=thread

  test-android:
    name: Test Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Android"
        uses: skiptools/swift-android-action@v2
